# Generated by Django 2.0.6 on 2018-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180627_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_type',
            field=models.CharField(default='article', max_length=200),
            preserve_default=False,
        ),
    ]
