# Generated by Django 2.0.6 on 2018-07-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180702_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
