# Generated by Django 2.0.6 on 2018-07-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180702_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('small_logo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='usedsoftware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.UsedSoftware'),
        ),
    ]
