# Generated by Django 2.0.6 on 2018-07-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180703_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='usedsoftware',
        ),
        migrations.AddField(
            model_name='usedsoftware',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Project'),
        ),
    ]
