# Generated by Django 2.0.6 on 2018-07-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_usedsoftware_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedsoftware',
            name='projects',
            field=models.ManyToManyField(blank=True, to='blog.Project'),
        ),
    ]
