# Generated by Django 2.0.7 on 2018-07-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180715_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='techspec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
