# Generated by Django 2.0.7 on 2018-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180718_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='techspec',
        ),
        migrations.AddField(
            model_name='article',
            name='techspec',
            field=models.BooleanField(default=False),
        ),
    ]
