# Generated by Django 2.1.2 on 2018-10-27 14:57

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('blog', '0021_auto_20180805_0230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
    ]
