# Generated by Django 2.1.2 on 2018-10-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20181027_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
