# Generated by Django 2.1.2 on 2018-10-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20181028_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_next',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='_previous',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
