# Generated by Django 2.1.2 on 2018-11-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20181031_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_next',
            new_name='next_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_previous',
            new_name='previous_post',
        ),
    ]
