# Generated by Django 2.1.2 on 2018-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20181101_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInstagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('oembed', models.CharField(max_length=5000)),
            ],
        ),
    ]
