# Generated by Django 2.1.2 on 2018-11-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_mailinglist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingList',
            new_name='Mailing_List',
        ),
    ]
