# Generated by Django 2.1.7 on 2019-07-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20181101_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.UsedSoftware'),
        ),
    ]
