# Generated by Django 2.1.7 on 2019-09-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20190726_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='platform',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
