# Generated by Django 3.0.2 on 2020-01-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_project_platform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialInstagram',
        ),
        migrations.RemoveField(
            model_name='post',
            name='techspec',
        ),
        migrations.AddField(
            model_name='project',
            name='showcase',
            field=models.BooleanField(default=False),
        ),
    ]
